sudo: required
services:
  - docker


before_install:
  - docker build -t ralucab/react-test -f ./client/Dockerfile.dev ./client 

script: 
  - docker run ralucab/react-test npm test -- --coverage
  
after_success:
  - docker build -t ralucab/multi-client ./client
  - docker build -t ralucab/multi-nginx ./nginx
  - docker build -t ralucab/multi-server ./server
  - docker build -t ralucab/multi-worker ./worker 
  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push image to docker hub
  - docker push ralucab/multi-client
  - docker push ralucab/multi-nginx
  - docker push ralucab/multi-server
  - docker push ralucab/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: complex
    env: Complex-env
    bucket_name: elasticbeanstalk-us-east-2-243348670467
    bucket_path: complex
    on:
      branch: master
    access_key_id:  AKIATRKFWBABXRBBMZW2
    secret_key_id:
      secure: guaDTnGA+J4ssF/p1BROJ5yq9UGUkPsnsp73hTIt  