version: "3"
services: 
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: "redis:latest"
  server:
    build: Dockerfile.dev
    context: ./server